### ISSUE TITLE
[feat] support STOMP

### ISSUE THREAD

**Issue by davidkhala** [oracle-devrel/oci-arch-queue-demo#4]
Could we have a sample of using STOMP to connect to OCI queue?

**Comment by BhaumikAbhishek** [comment]
STOMP code sample is now updated!

**Comment by davidkhala** [comment]
> STOMP code sample is now updated!

Would you mind pointing me out which PR including this?

**Comment by BhaumikAbhishek** [comment]
> > STOMP code sample is now updated!
> 
> Would you mind pointing me out which PR including this?

Pull request https://github.com/oracle-devrel/oci-arch-queue-demo/pull/5
